name: ds-env-devcontainer

services:
  workspace:
    image: ghcr.io/yukisakai1209/ds-env:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: "1001"
        USER_GID: "1001"
        USERNAME: vscode
    runtime: nvidia
    env_file:
      - ../.env
    volumes:
      # Bind mount SSH keys and config
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      # Keep nvidia driver mount
      - /run/nvidia:/run/nvidia:ro
      # Keep tmpfs mount
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1g
    entrypoint: ["/usr/local/bin/entrypoint_wrapper.sh"]
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command: sleep infinity
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
