name: devcontainer

services:
  workspace:
    image: ghcr.io/yukisakai1209/ds-env:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: "1001"
        USER_GID: "1001"
        USERNAME: vscode
    volumes:
      # Use short syntax for volume mounts
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      - ${HOME}/.codeium:/home/vscode/.codeium
      # Mount SSHFS directories that are already mounted on the host
      # - vermeer-volume:/home/vscode/vermeer
      # - magritte-volume:/home/vscode/magritte
      # - chagall-volume:/home/vscode/chagall
      # - picasso-volume:/home/vscode/picasso
      # - ncd-volume:/home/vscode/ncd
      # - xnef-data1-volume:/home/vscode/xnef-data1
      # - xnef-data2-volume:/home/vscode/xnef-data2
      # - cns-volume:/home/vscode/cns

    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined
    entrypoint: /usr/local/bin/entrypoint_wrapper.sh
    command: sleep infinity
    environment:
      - NVIDIA_DISABLE_REQUIRE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# volumes:
#   vermeer-volume:
#     driver: vieux/sshfs
#     driver_opts:
#       sshcmd: yuki1209@ncd-node01g:/home/vermeer/yuki1209
#       IdentityFile: /home/vscode/.ssh/id_rsa
#       allow_other: ""
#       uid: "1001"
#       gid: "1001"
#       LogLevel: DEBUG3
